// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVEEwF6jNsoCPrG7-As9eObhSkTTqw3gQ',
    appId: '1:984489449130:web:2019d3e9f9aa8f79a6e2d3',
    messagingSenderId: '984489449130',
    projectId: 'vimigoflutter',
    authDomain: 'vimigoflutter.firebaseapp.com',
    storageBucket: 'vimigoflutter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjoW8ZthocABY4_9yHgOWIj9S42A7IFko',
    appId: '1:984489449130:android:dbbee885791b0f5fa6e2d3',
    messagingSenderId: '984489449130',
    projectId: 'vimigoflutter',
    storageBucket: 'vimigoflutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBF3NTAjPvLmc8LM3iWd8TKwTSWPXqxlt4',
    appId: '1:984489449130:ios:dc7ac112952f1433a6e2d3',
    messagingSenderId: '984489449130',
    projectId: 'vimigoflutter',
    storageBucket: 'vimigoflutter.appspot.com',
    iosClientId: '984489449130-cuhemmdvep7ddldo6kvdbgov77c6it6q.apps.googleusercontent.com',
    iosBundleId: 'com.example.vimigoflutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBF3NTAjPvLmc8LM3iWd8TKwTSWPXqxlt4',
    appId: '1:984489449130:ios:dc7ac112952f1433a6e2d3',
    messagingSenderId: '984489449130',
    projectId: 'vimigoflutter',
    storageBucket: 'vimigoflutter.appspot.com',
    iosClientId: '984489449130-cuhemmdvep7ddldo6kvdbgov77c6it6q.apps.googleusercontent.com',
    iosBundleId: 'com.example.vimigoflutter',
  );
}
